### ISSUE TITLE
99 issues for 2.0 

### ISSUE THREAD

**Issue by corbett** [WhisperSystems/Signal-iOS#439]
## @corbett and @FredericJacobs 
- [ ] #370  Set "Conversation Safe Words" label in active conversation view
- [x] center the update/leave/members vertically on group convo dropdown
- [x] light gray hairline at top of inbox/archive switcher.
- [ ] light gray hairline at the bottom of the contact details dropdown.
- [ ] left transition for settings (some prototyping in reverse_settings_transition where I create a nave stack with the settings artificially at base)
- [x] text and image together (android has capability of sending)
- [x] not use directories backed up in iCloud for attachment storage
- [x] New Message view needs way to be refreshed when placeholder is displayed.

## @abolishme
*waiting for tasks*

## Completed
- [x] App Store-sized Icon + vectorial icon in repo TOP PRIORITY
- [x] tap and hold "my fingerprint" button for five seconds just does "abort secure session" ... not "shred", which was previously the red button on the fingerprint screen. remove red button. (ask moxie for details). if user wants to clear history, they delete the conversation in the inbox/archive view. (REMOVED)
- [x] improve twitter link image
- [x] constraints on the invisible buttons on the fingerprintview controller are off (check by setting the background to something non clear). TOP PRIORITY
- [x] on 6Plus bottom inbox/archive bar not constrained on left MEDIUM PRIORITY
- [x] delete button in inbox slightly poorly constrained on 6Plus (bleeds in) MEDIUM PRIOIRTY
- [x] constraint on table view cell, would be nice to have a longer preview message string (cuts off halfway through due to constraints)
- [x] review status bar changes and make suggestions (colors, size?) 
- [x] paperclip for attach should be ows_ blue (need an icon for this then that is that color)
- [x] in the build new conversation table, when you tap the phone icon, it should automatically launch a new call, and add the conversation to the inbox in the background (this should be a button before I hook it up) 
- [x] crash on search country code
- [x] in add new message hide phone if user not redphone user. (this should be a button before I hook it up)
- [x] BUG inbox on first launch doesn't update names (unless you select archive/inbox then updates) doing this selection in code doesn't work. mysterious yapdb related bug introduced. (@fredericjacobs will fix)
- [x] contact details dropdown should have translucent "vibrancy".
- [x] calls updates in JSQ styling. 
- [x] group updates in JSQ styling. 
- [x] crash on search country code
- [x] fix identity key tap to verify
- [x] image full screen view no longer has save button
- [x] searching for contact, create group, search bar doesn't dismiss
- [x] empty message has latest timestamp, can't be deleted
- [x] replace back button or nav bar by signal icon where appropriate (places it says "Signal" now)
- [x] format "my number" in settings
- [x] always show "hint" labels on contact security details screen. remove "hints button".
- [x] hide entire "their fingerprint" subview in contact security details unless the key material is present
- [x] #372 space between keyboard and button confirm 
- [x] #372 spinner or some progress indicator (@abolishme) disabling buttons while request outstanding
- [x] #371 delete account button row not resized
- [x] #371 Name, change, and phone number positioned incorrectly 
- [x] #368 speaker button assets
- [x] drop down on conversation view
- [x] Add cancel button to registration view
- [x] spinners on verification view
- [x] signal icon on phone number enter is not centered any more (everything else looks great)
- [x] #370 buttons needed
- [x] #446 replace empty group avatar
- [x] #369 buttons needed
- [x] verify code submit verification code missing spinner (other spinners are present)
- [x] empty message inbox/archive state
- [x] add phone icon to ContactTableViewCell for contacts with RedPhone
- [x] #364 this view needs complete stylizing within JSQ
- [x] style conversation view
- [x] redesign plus icon
- [x] design contact security screen
- [x] call status font color ... red has to change
- [x] define colors
- [x] #362 search bar is off
- [x] Set safe word pair text color to ows_blue
- [x] Call status "failed" or "call ended" red needs to change to ows red specified above
- [x] plugin #369 buttons needed
- [x] "send invite to unregistered number" should be ows_blue.
- [x] turn **vibrancy off** on all blue navigation bars, looks like it is on and changing the way our blue appears.
- [x] remove "info" button on network status
- [x] add status bar back in with different colors
- [x] fill out initializeTextInputBox method with fonts abolishme specified
- [ ] filter redphone only users from the contact list

![screen shot 2015-01-23 at 1 58 58 am](https://cloud.githubusercontent.com/assets/3347534/5870893/84886d2c-a2a3-11e4-83ec-0df3a97fa154.png)

### [Colors](http://color.hailpixel.com/#2090EA,92FF8A,FF3867,FFBB5C,)
- black: #080A00
- blue: #2090EA
- green: #92FF8A
- red: #FF3867
- gold: #FFBB5C

**Comment by abolishme** [comment]
![contact-details-guide](https://cloud.githubusercontent.com/assets/3347534/5846988/59bd193e-a196-11e4-95aa-c069c14ca4cf.jpg)
![contact-details](https://cloud.githubusercontent.com/assets/3347534/5846987/59b896b6-a196-11e4-8bd5-81e096af39a9.jpg)

**Comment by corbett** [comment]
spacing in the event of no phone in the middle? 61*2+?

On Wed, Jan 21, 2015 at 12:53 PM, Tyler Reinhard <notifications@github.com>
wrote:

> [image: contact-details-guide]
> <https://cloud.githubusercontent.com/assets/3347534/5846988/59bd193e-a196-11e4-95aa-c069c14ca4cf.jpg>
> [image: contact-details]
> <https://cloud.githubusercontent.com/assets/3347534/5846987/59b896b6-a196-11e4-8bd5-81e096af39a9.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/439#issuecomment-70938783>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by abolishme** [comment]
(61 * 2) + 66 = 188, where 66 is the width of the phone button. So the contact cards do not move if there is no phone icon.

**Comment by corbett** [comment]
I need to know what you want the width of the phone to be. that is the ?

On Wed, Jan 21, 2015 at 2:04 PM, Tyler Reinhard <notifications@github.com>
wrote:

> (61 * 2) + 66 = 188, where 66 is the width of the phone button. So the
> contact cards do not move if there is no phone icon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/439#issuecomment-70947556>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by abolishme** [comment]
yes @corbett, the phone is 66pts wide

**Comment by corbett** [comment]
reload

**Comment by corbett** [comment]
reload

**Comment by abolishme** [comment]
![missed-call](https://cloud.githubusercontent.com/assets/3347534/5852897/a0a49ef8-a1eb-11e4-9c97-8febd923e177.jpg)
![outgoing-record](https://cloud.githubusercontent.com/assets/3347534/5852896/a0a35822-a1eb-11e4-9db4-9ee6f832aa27.jpg)
![phone-record](https://cloud.githubusercontent.com/assets/3347534/5852898/a0a78064-a1eb-11e4-95f5-15ba6c375fc3.jpg)

Helvetica Neue Medium,then Helvetica Neue Light. both 8pt, ows_blue. am pm gets CAPS.

**Comment by abolishme** [comment]
![archive-empty-state](https://cloud.githubusercontent.com/assets/3347534/5853580/df0a2c06-a1f2-11e4-974d-a95672e62ba3.jpg)
![first-empty-state](https://cloud.githubusercontent.com/assets/3347534/5853582/df3fa85e-a1f2-11e4-952b-fea0e973a73c.jpg)
![inbox-tip](https://cloud.githubusercontent.com/assets/3347534/5853581/df3c2d96-a1f2-11e4-8335-253185c9009d.jpg)

some empty state brainstorms, the one with the line is a vector image called first-empty-state in the assets folder

**Comment by abolishme** [comment]
16pt helvetica neue bold
16pt helvetica neue regular, gray ish. (you got it)

**Comment by abolishme** [comment]
![screen shot 2015-01-22 at 8 23 11 pm](https://cloud.githubusercontent.com/assets/3347534/5869624/0ac7dcf2-a28a-11e4-9f1a-1c63008b73f7.png)

instead of the string "Signal" in the inbox/archive navigation bar, we want the signal logo. the file is already in the assets folder, and above is a demonstration of the button inset settings.

**Comment by corbett** [comment]
8 font is really small for the phone calls

**Comment by corbett** [comment]
height of the signal icon in nav bar should be 30x30

**Comment by wp9015362** [comment]
Hello,

I came here because I am wondering when TextSecure-iOS will finally be released, or, to be precise, when Signal will get messaging support.

I saw this page:

http://www.christinecorbettmoran.com/Signal-TextSecure-iOS

and it says:

> [...] We're proud to announce the equivalent of our RedPhone client
> on Android to now be available under Signal on iOS;
> your iPhone can finally make free encrypted calls,
> with messaging support coming soon: [...]

But what does "coming soon" mean?

Is there a progress tracker somewhere, where one could see how much is left to do?

And is there any ETA?

Just wondering.

Regards

**Comment by corbett** [comment]
The progress tracking is best seen by looking at the state of the current
repository and open issues. We will launch as soon as possible.

On Sun, Jan 25, 2015 at 10:00 AM, wp9015362 <notifications@github.com>
wrote:

> Hello,
>
> I came here because I am wondering when TextSecure-iOS will finally be
> released, or, to be precise, when Signal will get messaging support.
>
> I saw this page:
>
> http://www.christinecorbettmoran.com/Signal-TextSecure-iOS
>
> and it says:
>
> [...] We're proud to announce the equivalent of our RedPhone client
> on Android to now be available under Signal on iOS;
> your iPhone can finally make free encrypted calls,
> with messaging support coming soon: [...]
>
> But what does "coming soon" mean?
>
> Is there a progress tracker somewhere, where one could see how much is
> left to do?
>
> And is there any ETA?
>
> Just wondering.
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/439#issuecomment-71389581>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by helveticade** [comment]
Re:
> left transition for settings
Rethink required for the current primary action button "Done" as this is inconsistent with conventional iOS UX.

**Comment by helveticade** [comment]
@corbett @FredericJacobs thoughts on these?

![image](https://cloud.githubusercontent.com/assets/737950/5894396/38c72212-a4aa-11e4-85a6-845d391a421f.png)
vs
![image](https://cloud.githubusercontent.com/assets/737950/5894397/3c66ed08-a4aa-11e4-80be-7d105dddbe0c.png)


Context
__Option A__
![Option A](https://cloud.githubusercontent.com/assets/737950/5894407/63bc74b8-a4aa-11e4-96fd-bba19e1b5746.png)

__Option B__
![Option B](https://cloud.githubusercontent.com/assets/737950/5894402/52253208-a4aa-11e4-8096-c6e9eb2c6bd7.png)

**Comment by helveticade** [comment]
Re empty dashed avatar spaces
![image](https://cloud.githubusercontent.com/assets/737950/5894415/bb777a86-a4aa-11e4-90e1-3fe514f4982f.png)

**Comment by helveticade** [comment]
Examples of swipe actions on tableview cells:

__Move to Archive:__
![image](https://cloud.githubusercontent.com/assets/737950/5894597/d6a6776e-a4ad-11e4-9b96-90fb76043806.png)

__Back to Inbox:__
![image](https://cloud.githubusercontent.com/assets/737950/5894599/e11dae06-a4ad-11e4-9fbf-dbf9c5f12768.png)

**Comment by helveticade** [comment]
![image](https://cloud.githubusercontent.com/assets/737950/5907633/8cbf6056-a544-11e4-845e-7f42558496a6.png)

New onboarding designs, 99% the same as what we have but with header @ 16pt and a subheader at 14pt.

**Comment by helveticade** [comment]
## Home screen
- [ ] Update tab bar items with revised PDFs
- [ ] Blue outline around avatar-less contacts
- [ ] Red bar along the bottom of 6 + cells
- [ ] Replace swipe left actions with btnDelete--white asset
- [ ] Swipe left background colour to extend the length of the cell (eg like swipe right blue length)
- [ ] Replace swipe right buttons with cellBtnMoveToArchive--blue and cellBtnMoveToInbox--blue respectively

## Settings  
- [ ] Transition
- [ ] Done icon replaced with btnSignal
- [ ] Swap blue and grey for Registered Number and Change (change doesn't look like a button)
- [ ] UI Switch on should be Signal Blue.
- [ ] Update green colour (tbc)

## New Message  
- [ ] Phone icon out of alignment on 6+

## New Group
- [ ] Create button should be btnCompose--white
- [ ] Add people to be a tableview header (ask @helveticade for creatives)

**Comment by corbett** [comment]
Updated issues:
## Todos

### Inbox / Archive
- [ ] Slight alignment issue with avatarless contacts (initials apparently slightly off)

### Settings  
- [ ] Stretch goal: Transition a nav transition back

### Conversation
- [ ] Text alignment revision on new message bar.
- [ ] Fade between call and send buttons

### Groups + Messages
- [ ] More padding above and below status messages (8 pt?)
- [ ] Attachment button should be 21x25 (will need QA here)

### Onboarding
- [ ] Header 18pt Medlum, Subheader 14pt Regular
- [ ] Better alignment for everything onboarding (work with Cade)
- [ ] stretch goal: put in tutorial a la Android.

### Empty States
-[ ] empty state for loading on launch in message compose should be uiEmpty with spinner in the middle of it and text "Loading contacts"
-[ ] empty state for loading on launch in message compose should be "None of your contacts have Signal.\nWhy don't you invite some". Screenshot in previous comment

**Comment by FredericJacobs** [comment]
Good for now.
