### ISSUE TITLE
98 Issues for Beta Polish

### ISSUE THREAD

**Issue by abolishme** [WhisperSystems/Signal-iOS#577]
The following represents the smallest necessary changes to ship the 2.0 release. Note that required assets are on their way. `(d/w)` indicates a dark solid icon on a white background, `(w/d)` indicates mostly white icons on a blue or dark background.

## completed
- [x] Change navigation bar title to "Conversations"
- [x] Change number in tab bar to the number of unread messages.
- [x] Gray border needs to be removed from group avatar circles. -> #581 needs review
- [x] Users with no avatar should be solid color circles with randomly selected (*see avatar fills below*) fills, fills should stay the same per contact. Initials should be white. -> #581 needs review
- [x] Use new Cancel button icon
- [x] Use new Add Group button icon
- [x] Use new Call Contact (d/w) button icon
- [x] Back button label should just be the icon, not the text.
- [x] Use new Back button icon
- [x] With the exception of the first launch inbox state, none of the empty states should include any artwork
- [x] First Launch Inbox State [should read][first-launch-inbox]: `Start your first Signal conversation! Tap on the + button.`
- [x] Empty Inbox State [should read][empty-inbox] `Done. Done. Done. Tip: add a conversation as a reminder!`
- [x] First Launch Archive State [should read][first-launch-archive] `Save conversations for reference. You can swipe conversations into your Archive from the Inbox`
- [x] Empty Archive State [should read][empty-archive] `Squeaky Freaking Clean. None. Zero. Zilch. Nada.`
- [x] Tapping signal icon should return user to last conversations mode (inbox or archive, whichever was last used). *See issue #580*.
- [x] Remove incoming/outgoing call icons from conversation notes. Should appear [like this][conversation-note]. 
- [x] Call button should be removed from compose bar (when no text is in the input, or ever).
- [x] Call button should move to right side of nav bar, and be solid white. 
- [x] Send button in compose bar should be the word `Send`.  
- [x] Attachment icon should be paperclip 
- [x] Attachment options should be `Choose from Library...`, or `Take Photo or Video` 
- [x] Change Signal icon to close button (temporary until next release)
- [x] Settings Gear icon should be solid white

## Global
- [x]  #597 needs review
- [x] Remove gray bar beneath Navigation Bar, it can be [seen here](https://cloud.githubusercontent.com/assets/3347534/6089571/b1b0de20-ae32-11e4-8138-057384cb0cd9.png).
 
## Registration
- [ ] Registration Screen Title constraints are incorrect in 5s. (@abolishme)

## Conversation View 
- [x] #596 needs review
- [x] #583 needs review
- [x] Should use new Inbox and Archive icons
- [x] New Conversation icon should be a plus (*see new_conversation_icon*).
- [x] Blue dot should be removed from beneath inbox/archive icons.
- [x] Inbox/Archive icons need to be lowered, vertically centered in container.

## New Conversation View 
- [x] #590 needs review

## New Group View
- [ ] Use new Group Avatar Prompt button icon

### Empty States 
- [x] first launch empty archive state should read `Clean Up Your Conversations. You can archive inactive conversations for later from your Inbox.` attn: @FredericJacobs 
- [x] #583 needs review 

## Settings (@FredericJacobs)
- [x] Should be a confirmation modal when you tap destroy account.
- [x] Change Connection status to this green: `rgb(66,191,64)`, and make font Helvetica Neue Medium. @FredericJacobs 

[conversation-note]: https://cloud.githubusercontent.com/assets/3347534/5852896/a0a35822-a1eb-11e4-9db4-9ee6f832aa27.jpg

[first-launch-inbox]: https://cloud.githubusercontent.com/assets/3347534/5853582/df3fa85e-a1f2-11e4-952b-fea0e973a73c.jpg

[empty-inbox]: https://cloud.githubusercontent.com/assets/3347534/5853581/df3c2d96-a1f2-11e4-8335-253185c9009d.jpg

[first-launch-archive]: 

[empty-archive]: https://cloud.githubusercontent.com/assets/3347534/5853580/df0a2c06-a1f2-11e4-974d-a95672e62ba3.jpg

EDIT by @FredericJacobs, @corbett

Anything that has not been implicitly attributed to someone else is on @FredericJacobs's TODO list.

**Comment by abolishme** [comment]
assets forthcoming

**Comment by abolishme** [comment]
colors forthcoming

**Comment by helveticade** [comment]
I'm concerned about the language in the app, still, and also these new icons. Outside of the UX issues around how Signal 2.0 works, some other issues are:

- New Conversation and New Group use different metaphors. 
- Call button introduces unclear iconography
- Archive / Inbox don't offer any real explanations as to their difference. Especially on initial empty state
- Icons introduce non-OS specific metaphors.
- Empty states are highly americanised and are unfamiliar to non-American users

By themselves, none of these are serious issues. But Signal 2.0's messaging UX is an unusual paradigm. Iconography that departs from convention when combined with this new UX paradigm will make Signal more confusing to use.

**Comment by corbett** [comment]
I would echo all these concerns and in particular encourage the call
feature to be easy to get to. as an everyday user of the app, I love it. I
would also say that as someone who has spent a lot of time in Europe, that
language doesn't translate well and is confusing to non-Americans.

On Sat, Feb 7, 2015 at 7:31 AM, Cade <notifications@github.com> wrote:

> I'm concerned about the language in the app, still, and also these new
> icons. Outside of the UX issues around how Signal 2.0 works, some other
> issues are:
>
>    - New Conversation and New Group use different metaphors.
>    - Call button introduces unclear iconography
>    - Archive / Inbox don't offer any real explanations as to their
>    difference. Especially on initial empty state
>    - Icons introduce non-OS specific metaphors.
>    - Empty states are highly americanised and are unfamiliar to
>    non-American users
>
> By themselves, none of these are serious issues. But Signal 2.0's
> messaging UX is an unusual paradigm. Iconography that departs from
> convention when combined with this new UX paradigm will make Signal more
> confusing to use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/577#issuecomment-73353989>
> .
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by abcdev** [comment]
@helveticade  and @corbett  +1
I don't even see an argument against using string labeled buttons instead of icon in some cases.

Another point I want to bring up is the "Send" button which is borrowed form the Android version.
What is the reasoning behind this decision?

- the Textsecure version was oriented along the Android SMS Messaging (AOSP) design. (green arrow)
- as Textsecure can seamlessly integrate with Android this is the obvious way to go

Both of this doesn't apply to iOS. The system messaging app (also a lot of alternatives) state "Send" in form of a string.

**Comment by abolishme** [comment]
Hey all. As far as the language, that can be localized if you have other ideas for other language sets, but @moxie0 said, quote "that is the perfect voice" about that text after we brainstormed, and i agree so that's what we're going with.

> New Conversation and New Group use different metaphors.

This is because the devs couldn't build the new conversation flow i designed for this release. building a new conversation, whether a group or individual, will be one single flow in a future release.

> Another point I want to bring up is the "Send" button which is borrowed form the Android version.

agree, that's going for sure.

as far as the other concerns ... after a conversation with @moxie0, we decided to come up with my minimum changes for a shippable app. These are my minimum requirements. The current beta isn't a full implementation of my design, and neither will it be once these changes are made. this is just the **minimum** amount of work i think we need to do to make the app professional. @helveticade we just don't see eye to eye about "non-OS specific metaphors", and i'm not going to debate about it anymore, but i appreciate you speaking your mind about it.

As far as i know, this is what we are doing. I'll be working with fred today (over the phone) about how to go about making these changes as i specifically audited the app for the least-effort changes. thanks for the feedback everyone.

**Comment by corbett** [comment]
@abolishme we need an icon for the paperclip for the attachments, can't find it in pixelapps.

**Comment by abolishme** [comment]
@FredericJacobs let's add a confirmation modal to the call icon. `Would you like to use Signal to make a secure call to Moxie Marlinspike? Cancel. Yes.`

**Comment by abolishme** [comment]
hey @corbett and @FredericJacobs, are you two still tracking the unchecked subissues on #439, or should I add them here, there are just a few i think should still be done.

**Comment by corbett** [comment]
add them here.

On Fri, Feb 13, 2015 at 4:07 PM, Tyler Reinhard <notifications@github.com>
wrote:

> hey @corbett <https://github.com/corbett> and @FredericJacobs
> <https://github.com/FredericJacobs>, are you two still tracking the
> unchecked subissues on #439
> <https://github.com/WhisperSystems/Signal-iOS/issues/439>, or should I
> add them here, there are just a few i think should still be done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/issues/577#issuecomment-74349382>
> .
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Replaced by #598
